#!/bin/sh

sonar-scanner \
  -Dsonar.projectKey=gpp-common \
  -Dsonar.organization=gpp \
  -Dsonar.sources=. \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=a1dfc8b3808a99bf6c6662ed4b06952fd6f25da4
